### ISSUE TITLE
Miscalculating zoom level under some conditions?

### ISSUE THREAD

**Issue by neelsmith** [ryanfb/dzi-dl#8]
I'm sporadically hitting failures alongside succesful downloads.  Failures produce many messages like this,

`WARNING: HTTP Error 404: Not Found. Tile http://mss.bmlonline.it/fcgi-bin/iipsrv.fcgi?Zoomify=\\TECA-NAS\\Teca\\Plutei\\Lotto03\\.\\P000898_32.03\\pyr\\Plut._32.03_0702.tif/TileGroup1/4-13-15.jpg (row 15, col 13) does not exist on the server.`

Ending with a message like this:

`Empty input file`
`WARNING: Image '/data/laur32_3_0702.jpg' is missing 229 tiles. You might want to download the image at a different zoom level (currently 4) to get the missing parts.`

Here is a pair of cases where the first consistently fails, and the second consistently succeeds:

```
docker run -v $(pwd):/data ryanfb/dezoomify -b 'http://mss.bmlonline.it/fcgi-bin/iipsrv.fcgi?Zoomify=\\TECA-NAS\\Teca\\Plutei\\Lotto03\\.\\P000898_32.03\\pyr\\Plut._32.03_0702.tif' /data/laur32_3_0702.jpg

docker run -v $(pwd):/data ryanfb/dezoomify -b 'http://mss.bmlonline.it/fcgi-bin/iipsrv.fcgi?Zoomify=\\TECA-NAS\\Teca\\Plutei\\Lotto03\\.\\P000898_32.03\\pyr\\Plut._32.03_0703.tif' /data/laur32_3_0703.jpg
```

I noticed in the Bodleian's metadata for these files at 
<http://mss.bmlonline.it/paginelibro.ashx?Id=AWOIewdrI1A4r7GxMH6E> that the failing images consistently had different and smaller image dimensions than the images that downloaded successfully.  Here is the pair of metadata entries for the two example files above:

 {"alt":"Carta: 347v",
   "magid":"AWOIeosnI1A4r7GxMH0w",
   "url":"\\\\TECA-NAS\\Teca\\Plutei\\Lotto03\\.\\P000898_32.03\\pyr\\Plut._32.03_0702.tif",
   "preview":"./P000898_32.03/pre/Plut._32.03_0702.jpg",
   "tifHeight":"4103",
   "tifWidth":"3560",
   "height":-8,
   "width":-7,
   "groupId":"702",
   "coeff":0.875,
   "imgId":"702"}

   {"alt":"Carta: 348r",
     "magid":"AWOIeosnI1A4r7GxMH0w",
     "url":"\\\\TECA-NAS\\Teca\\Plutei\\Lotto03\\.\\P000898_32.03\\pyr\\Plut._32.03_0703.tif",
     "preview":"./P000898_32.03/pre/Plut._32.03_0703.jpg",
     "tifHeight":"3893",
     "tifWidth":"3188",
     "height":-8,
     "width":-7,
     "groupId":"703",
     "coeff":0.875,
     "imgId":"703"},

Is it possible that the script is calculating tile levels for a larger image and trying to apply it to all images?  Or otherwise asking for the wrong number of levels?

**Comment by neelsmith** [comment]
(Also possible I'm stupidly overlooking something obvious.)

**Comment by ryanfb** [comment]
I was a little confused, so some clarification - the [`ryanfb/dezoomify` Docker image](https://hub.docker.com/r/ryanfb/dezoomify) is a Dockerized build of [`dezoomify-py`](https://github.com/lovasoa/dezoomify-py/), which hasn't been updated in some time. The Docker image for `dzi-dl` (this repo) is at [`ryanfb/dzi-dl`](https://hub.docker.com/r/ryanfb/dzi-dl).

In any case, I think the bmlonline.it images aren't using DeepZoom, they're using Zoomify. An updated/maintained command-line version of dezoomify which can handle these is [`dezoomify-rs`](https://github.com/lovasoa/dezoomify-rs) (I haven't made a Docker image for this yet).

However, I see similar errors with it on image 702, although image 703 works, while also warning about a tile count mismatch:
```
dezoomify-rs -l 'http://mss.bmlonline.it/fcgi-bin/iipsrv.fcgi?Zoomify=\\TECA-NAS\\Teca\\Plutei\\Lotto03\\.\\P000898_32.03\\pyr\\Plut._32.03_0703.tif/ImageProperties.xml'
[2020-05-15T12:44:49Z WARN  dezoomify_rs::zoomify::image_properties] The computed number of tiles (285) does not match the number of tiles specified in ImageProperties.xml (208)
[ETA:0s] ########################################  208/208  Finished tile download
Saving the image to dezoomified.jpg...
Saved the image to dezoomified.jpg
Done!
```
702 has many missing tiles no matter how I set the retries or even if I attempt a different zoom level. I was tempted to say the issue might be that the tiles are actually corrupt on the server, however if I go to the interactive viewer page (<http://mss.bmlonline.it/s.aspx?Id=AWOIeosnI1A4r7GxMH0w#/oro/702>), the tiles are a little slow but they still load. So I'm not really sure what's going on here, may have to investigate with network inspector.

**Comment by ryanfb** [comment]
A workaround seems to be to just use dezoomify-rs's [custom YAML downloader](https://github.com/lovasoa/dezoomify-rs/wiki/Usage-example-for-the-custom-YAML-dezoomer). Save this as `tiles.yaml`:

```
url_template: "http://mss.bmlonline.it/fcgi-bin/iipsrv.fcgi?Zoomify=\\\\TECA-NAS\\Teca\\Plutei\\Lotto03\\.\\P000898_32.03\\pyr\\Plut._32.03_0{{page}}.tif/TileGroup1/{{zoom_level}}-{{x/256}}-{{y/256}}.jpg"

variables:
  - name: x
    from: 0
    to: 3560
    step: 256

  - name: y
    from: 0
    to: 4103
    step: 256
  - name: page
    value: 702
  - name: zoom_level
    value: 5

headers:
  Referer: http://mss.bmlonline.it/
```
And then run `dezoomify-rs tiles.yaml`.

You can then change the page with the corresponding metadata for the resolution + max zoom level. So it looks like this is an issue with this particular image - either dezoomify-rs is miscalculating the max zoom level, or bmlonline.it's Zoomify implementation is, because it's off-by-one for this image (it may well be that they're all off-by-one, and that's what results in the *warning* for the tile count mismatch on other images - it's just that when the *max* zoom level is coincidentally calculated to be the same, it can still successfully download it by using the number of tiles specified in `ImageProperties.xml`).

**Comment by neelsmith** [comment]
Whew!  Thanks for the clarification.  Will look into trying your suggestion!
